### PR TITLE
Add description to Docker part

### PR DESCRIPTION
**Pull request by ChangYuHsuan**

### CODE REVIEW

**Comment by huckl3b3rry87** [comment]
thanks!

**Comment by huckl3b3rry87** [comment]
Is there a volume that stores the results from rosbag? Or is that something that still needs to be done?

Also, can you add a picture of what this looks like? Something like the one here
https://docs.docker.com/storage/#choose-the-right-type-of-mount
Except specific to our project

**Comment by ChangYuHsuan** [comment]
I thought the shared_dir is the folder that we store the result from rosbag.
If the result will be stored in [src/system/data/ directory](https://github.com/JuliaMPC/MAVs/tree/master/ros/src/system/data), then the volume is set because we already share src/ directory. 

And I will add a quick picture.

**Comment by huckl3b3rry87** [comment]
Can we add another volume? Putting data in the src folder is bad practice,
then the project will be changing based off of random data

**Comment by ChangYuHsuan** [comment]
No problem, I will deal with it. 
Adding a volume outside of MAVs directory, so that it would not effect git stuffs due to random data generated by demo. Am I right about your idea?

**Pull request merged**
